# Generated by Django 2.0.5 on 2018-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('implementer', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
