# Generated by Django 2.0.5 on 2018-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180527_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
