# Generated by Django 2.0.5 on 2018-05-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180527_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
    ]
