# Generated by Django 2.0.5 on 2018-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_task_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete='CASCADE', to='task.Task')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
